import os
from typing import Tuple


def _env_float(name: str, default: float) -> float:
    return float(os.environ.get(f"SHERLOCK_{name}", default))


def _env_int(name: str, default: int) -> int:
    return int(os.environ.get(f"SHERLOCK_{name}", default))


MAX_GAP_FOR_TURN_MERGE_SECONDS: float = _env_float("MAX_GAP_TURN_MERGE", 1.5)

LATE_JOIN_PENALTY_LOG_ODDS: float = _env_float("LATE_JOIN_PENALTY", -0.3)

LATE_JOIN_THRESHOLD_SECONDS: float = _env_float("LATE_JOIN_THRESHOLD", 180.0)

LEAVE_GRACE_WINDOW_SECONDS: float = _env_float("LEAVE_GRACE_WINDOW", 600.0)

INTERVIEWER_NAME_MATCH_THRESHOLD: float = _env_float("INTERVIEWER_NAME_THRESHOLD", 90.0)

CANDIDATE_COLLISION_GUARD_THRESHOLD: float = _env_float("CANDIDATE_COLLISION_GUARD", 78.0)

KNOWN_INTERVIEWER_ELIMINATION_DELTA: float = _env_float("INTERVIEWER_DELTA", -6.0)

KNOWN_INTERVIEWER_CATEGORY_CAP: float = _env_float("INTERVIEWER_CAP", 8.0)

CANDIDATE_NAME_MATCH_THRESHOLD: float = _env_float("CANDIDATE_NAME_THRESHOLD", 82.0)

CANDIDATE_NAME_MATCH_DELTA: float = _env_float("CANDIDATE_NAME_DELTA", 1.2)

CANDIDATE_NAME_MATCH_CATEGORY_CAP: float = _env_float("CANDIDATE_NAME_CAP", 3.0)

SILENCE_INITIAL_THRESHOLD_SECONDS: float = _env_float("SILENCE_INITIAL_THRESHOLD", 300.0)  # 5 min

SILENCE_CHECK_INTERVAL_SECONDS: float = _env_float("SILENCE_CHECK_INTERVAL", 300.0)  # 5 min

SILENCE_ELIMINATION_INCREMENT_DELTA: float = _env_float("SILENCE_INCREMENT", -1.0)

SILENCE_CATEGORY_CAP: float = _env_float("SILENCE_CAP", 3.0)

SILENCE_POSITIVE_EVIDENCE_DAMPENING_FACTOR: float = _env_float("SILENCE_DAMPENING", 0.5)
SILENCE_AUTOMATED_NAME_AMPLIFIER_DELTA: float = _env_float("SILENCE_AUTOMATED_AMPLIFIER", 0.0)

MIN_INFORMATIVE_WORD_COUNT: int = _env_int("MIN_INFORMATIVE_WORD_COUNT", 4)

MIN_ASR_CONFIDENCE_FOR_CLASSIFICATION: float = _env_float("MIN_ASR_CONFIDENCE", 0.6)

MIN_CLASSIFIER_CONFIDENCE: float = _env_float("MIN_CLASSIFIER_CONFIDENCE", 0.65)

PATTERN_ESTABLISHMENT_TURN_COUNT: int = _env_int("PATTERN_ESTABLISHMENT_TURN_COUNT", 5)

EVALUATIVE_QUESTION_BASE_DELTA: float = _env_float("EVALUATIVE_QUESTION_BASE_DELTA", -0.4)

EVALUATIVE_QUESTION_ESTABLISHED_DELTA: float = _env_float("EVALUATIVE_QUESTION_ESTABLISHED_DELTA", -1.5)

CANDIDATE_NARRATIVE_BASE_DELTA: float = _env_float("CANDIDATE_NARRATIVE_BASE_DELTA", 0.5)

CANDIDATE_NARRATIVE_ESTABLISHED_DELTA: float = _env_float("CANDIDATE_NARRATIVE_ESTABLISHED_DELTA", 2.0)

TRANSCRIPT_ROLE_CATEGORY_CAP: float = _env_float("TRANSCRIPT_ROLE_CATEGORY_CAP", 6.0)
INTERVIEWER_ROLE_CATEGORY_CAP: float = TRANSCRIPT_ROLE_CATEGORY_CAP
CANDIDATE_ROLE_CATEGORY_CAP: float = TRANSCRIPT_ROLE_CATEGORY_CAP

SPOKEN_INTRODUCTION_DELTA: float = _env_float("SPOKEN_INTRODUCTION_DELTA", 2.5)

SPOKEN_INTRODUCTION_CATEGORY_CAP: float = _env_float("SPOKEN_INTRODUCTION_CATEGORY_CAP", 3.0)

TURN_TAKING_AFTER_INTERVIEWER_DELTA: float = _env_float("TURN_TAKING_AFTER_INTERVIEWER_DELTA", 0.3)

TURN_TAKING_CATEGORY_CAP: float = _env_float("TURN_TAKING_CATEGORY_CAP", 2.0)

SCREENSHARE_AMPLIFICATION_FACTOR: float = _env_float("SCREENSHARE_AMPLIFICATION_FACTOR", 0.4)


CONFIDENCE_MAGNITUDE_ENTER_THRESHOLD: float = _env_float("CONFIDENCE_MAGNITUDE_ENTER", 4.0)

CONFIDENCE_ENTROPY_ENTER_THRESHOLD: float = _env_float("CONFIDENCE_ENTROPY_ENTER", 0.4)

CONFIRMED_MAGNITUDE_EXIT_THRESHOLD: float = _env_float("CONFIRMED_MAGNITUDE_EXIT", 2.5)

CONFIRMED_ENTROPY_EXIT_THRESHOLD: float = _env_float("CONFIRMED_ENTROPY_EXIT", 0.6)

METADATA_MISMATCH_TIME_THRESHOLD_SECONDS: float = _env_float("METADATA_MISMATCH_TIME", 600.0)  # 10 min

METADATA_MISMATCH_MAX_SCORE_FLOOR: float = _env_float("METADATA_MISMATCH_SCORE_FLOOR", 1.0)

_AUTOMATED_KEYWORDS_DEFAULT = (
    "recorder,notetaker,note taker,note-taker,transcription bot,meeting bot,"
    "otter.ai,otter pilot,fireflies,gong.io,chorus.ai,fathom"
)
AUTOMATED_PARTICIPANT_NAME_KEYWORDS: Tuple[str, ...] = tuple(
    kw.strip()
    for kw in os.environ.get(
        "SHERLOCK_AUTOMATED_KEYWORDS", _AUTOMATED_KEYWORDS_DEFAULT
    ).split(",")
    if kw.strip()
)